### ISSUE TITLE
severity equation

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#28]
Sorry, 'severity' is pdsi, right? I'm getting the same issue as smdi where the results don't align with outside examples I'm seeing. I know the index won't be very accurate until I go decades back but again, we're talking orders of magnitude.

Example from March 1 2016, 14 months into the run, NCEP/CMORPH, 0.25, entire region: http://i.imgur.com/Mzly8b9.png

**Comment by kandread** [comment]
Severity is not PDSI, it's calculated from the empirical CDF of soil moisture as 100-Si where Si is the percentile relative to a climatology. Range of values is 0-100.

**Comment by AdamJDuncan** [comment]
OK... sorry, what paper is this from? I don't really understand the "climatology" parameter here.

**Comment by kandread** [comment]
Climatology is the data used to build the CDF, the larger the sample the more accurate it will be. This paper contains more details http://journals.ametsoc.org/doi/abs/10.1175/JHM450.1

**Comment by AdamJDuncan** [comment]
OK thanks I understand now. Definitely needs data back to '81, which I've been fetching since this morning (will test out SRI when that's done as using SQL in QGIS cancels all other operations... the clipped monthly SRI 1 & 3 maps for 2015/16 were sent to M for the mock-up late last night as the offending pixels weren't in the study area).

If the neighbourhood's 3x3 I guess the b-box needs to be extended 0.25 degrees on each side... are there any indices we'll be using which require a larger extension than that?

**Comment by kandread** [comment]
Not sure I understand the 3x3 neighborhood, are you referring to the severity calculation? That is done on a per-pixel basis so the bounding box shouldn't matter.

**Comment by AdamJDuncan** [comment]
Areas of the LMR on the boundaries will affected by nodata in adjacent pixels during the spatial smoothing process, right? Would you say it's not enough to worry about?

This actually leads to related questions:
1. Min threshold for clustering... is it 10 pixels, as per the paper? (If there's a drought in western Myanmar associated with Eastern India/Bangladesh but not the rest of the study area, it won't move on to subsequent calculations) 
2. Something I've been putting off... how important in your opinion is it to pull in the entire upstream basins of all rivers that flow into the region from the north? I'm assuming incoming runoff from higher elevations outside the study area is "0". Should we worry about basal discharge from the far reaches of the Mekong/Irawaddy/Salaween (essentially doubling the processing time), or would a few pixels -- accounting for groundflow that hasn't yet entered the stream network -- suffice?

**Comment by AdamJDuncan** [comment]
(Sorry the question about clustering may seem a little obscure I think this is one of the most important outputs and I think that on the Servir/MRC end of things we should stop thinking of every output as being deliverable months from now... preparation for agronomic forecasting and crop yield calibration will take work, but there are in fact hydrological outputs that are actually close to deliverable now, and I want to get them right)

**Comment by kandread** [comment]
Severity calculations don't involve the spatial clustering approach described in the paper. That approach was used to identify drought events across space and time, given that pixels can go in and out of drought from month to month. The section of the paper that applies here is section 4 "Soil moisture and runoff percentiles" and that is calculated for each pixel _independently_. 
Regarding your second question, if you're going to calculate streamflow (by running the VIC routing model) I'd say that they probably will have an impact. I'd calculate the contributing area upstream of your area's boundaries first and see how they compare to the drainage area at the basin outlets. If you're only focusing on runoff, including upstream pixels won't have any impact since VIC assumes that there's no horizontal transport of water at the macroscale.
