### ISSUE TITLE
Current situation of assimilation dataset downloads

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#54]
(For the inland Kayah State, Myanmar. I'm happy with SMOS alone but would like to use Modis 15 & 16 as well.)

```
[domain]
minlat: 19
maxlat: 20
minlon: 97
maxlon: 98
```
# SOIL MOISTURE
## SMOS

Works.
## SMAP

```
[smap]
startdate: 2015-05-01
enddate: 2015-05-15
```

```
WARNING: Missing options for local dataset smap. Nothing ingested!
```
## AMSRE

Ingests data, but extremely slow... I tried running it overnight last week and it only went through a few dates. Guessing it's a server-side issue.
# EVAPOTRANSPIRATION
## MOD16

Site has been down for a while; seems to be an issue in North America as well. I'll email the providers.
# LEAF AREA INDEX
## MCD15

Issue with line 67... looking at it today (LAI2.tif is not being created)

```
proc = subprocess.Popen(["gdalwarp", "-t_srs", "'+proj=latlong +ellps=sphere'", "-tr", str(res), str(-res), "{0}/lai1.tif".format(outpath), "{0}/lai2.tif".format(outpath)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

```

**Comment by AdamJDuncan** [comment]
If we're performing assimilation on soil moisture with observed data, is there any reason to perform assimilation on the model's inputs, anyway?  Are the corrections to the inputs "cancelled out" by corrections to the result? I assume I'm wrong but could you explain why? Thanks.

**Comment by kandread** [comment]
Hey @AdamJDuncan, apologies for the very late reply. If I understand your question correctly, we're not really performing assimilation on the model inputs (precipitation, temperature). The assimilation essentially "compares" the model-predicted observation with the actual observation and adds that difference (weighted by the gain matrix) to the prior model estimate of what you're trying to update.
You could theoretically correct the precipitation in order to get the model prediction to be close to the observed soil moisture, and in that case you're right there might be little impact if you assimilate the same observation. How little of an impact would depend on whether the relationship between the model input and the observation is linear enough (and Gaussian) so it can be represented through the Kalman Filter.
Hope this makes sense!

**Comment by kandread** [comment]
I've made a number of fixes and updates on these datasets and tested them out. Closing this but feel free to reopen if you still have issues.
