### ISSUE TITLE
Severity index -- too much day-to-day variability?

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#55]
Hi Kostas I'm looking in your article " Twentieth-Century Drought in the Conterminous United States " and feel RHEAS's "severity/SAD" results have higher elasticity than I should be expecting. Here's Severity measured for the first 13 days at five points in the LMR (this is the fifth of ten ensembles, I believe):

![capture](https://cloud.githubusercontent.com/assets/16409628/18903808/3f362784-8585-11e6-9914-e98eb3072cef.PNG)

Is the equation supposed to lead to these results? Is this index a better indicator of drought if averaged by month? Thank you.

**Comment by kandread** [comment]
Severity is basically 1 minus the percentile from climatology, so your time series will always map from 0-1 (CDF). If the climatology is short, some of your "dry" values will be classified as "wet" since everything's relative to the sample you have (i.e. climatology). I suspect that is what's going on here. Averaging monthly will remove some of that variability, but you will still have the same fundamental problem. Assuming that you have a short climatology, I suggest generating a longer (20-30 year) baseline simulation and then re-running.

**Comment by AdamJDuncan** [comment]
OK thanks for your explanation.

How does this 20-30 year "baseline simulation" work? I can run a nowcast, then a forecast, and the latter will incorporate the former's drought index mean/std/skew/kurtosis into its calculations? CHIRPS and NCEP go back to 1985 in the DB. How do I use this to our benefit for forecasts? Initialization file only contains information on current soil state, right? Do I just run a nowcast first in the same schema?

**Comment by kandread** [comment]
You can run a nowcast for a long enough time period up to the initialization date for your forecasts. So the forecast severity will utilize the previous run as the climatology.

**Comment by AdamJDuncan** [comment]
Cool, didn't know it had a memory like that... will run a 30-year for the entire region over the weekend.
